# Research Questions and Goals

## Research Questions

### Pneumococcal Carriage Load (*Spn Density*)

1.  Quem tem maior chance de desenvolver *carriage*?
2.  Existem outros grupos de risco?
3.  Quais sao as variaveis importante p/ predizer *carriage*?
4.  Existem agrupamentos de individuos baseado em seu perfil de expressao?

### Gene Expression (*RNA-Seq*)

#### At Baseline

1.  Which genes are perturbed between C+ and C- among man/woman?
2.  Which pathways are enriched between C+ and C- among man/woman?
3.  Which genes can predict *carriage* in men/women?

#### Day~x~ vs Baseline

1.  Which genes are perturbed among C+ man/women?
2.  Which pathways are perturbed among C+ man/women?
3.  Which genes are perturbed among C- man/women?
4.  Which pathways are perturbed among C- man/women?

### Cytokines (*Luminex*)

#### At Baseline

1.  Which cytokines are perturbed between C+ and C- among man/woman?

#### Day~x~ vs Baseline

1.  Which cytokines are perturbed among C+ man/woman?
2.  Which cytokines are perturbed among C- man/woman?

### Hormone Levels

### Cell Recruitment (*Flow Cytometry*)

## Objectives

The goal of this study is to evaluate how sex and ageing might affect the immune responses to Spn carriage development and its control, to understand intrinsic factors that may give protection for some carriers but increase susceptibility to diseases in others. More specifically,

This will be done by identifying the components and describing their relationships of different layers of human biology during the response to Spn, and further modelling the complexity of the overall response by integrating each level. At first, a single-omics approach will be used to upon each cohort and data type to:

-   profile the overall immune response of adults to Spn infection

-   profile the overall immune response of adults to Spn infection, stratified by sex

-   Identify sex-specific components and/or behaviors in immune response profiles

-   profile the overall immune response of elderlies to Spn infection

-   Identify age-specific components and/or behaviors in immune response profiles among elderlies and adults

-   profile the overall immune response of elderlies to Spn infection, stratified by sex

-   Identify sex-specific components and/or behaviors in immune response profiles among elderlies

-   Identify age-specific components and/or behaviors in immune response profiles among elderlies and adults of same-sex

-   Select the main components affected by sex and age to Spn infection

With the main components selected, different layers of the nasal mucosa will be integrated with multi-omics approaches to describe the main components and its interactions related to sex and ageing factors during Spn infection, carriage development and influenza vaccine interactions.
