# Research Questions

What are the main sex-related factors in healthy adults that

1.  **What are the main host factors that predispose susceptibility to pneumococcal carriage in young healthy adults?**

    1.  What are the main host factors that can predict the development of carriage? *Data:* rna-seq, Luminex, flow, microbiome *Analysis:* Data Integration, Feature selection, Machine Learning, Network analysis

    2.  What are the main perturbations and gene expression signatures associated to development of carriage? *Data:* rna-seq *Analysis:* DEGs, Co-Expression, MDP, Characteristic Direction, Pathway Analysis, Network analysis

    3.  What are the main perturbations and immunological response signatures associated to development of carriage? *Data:* luminex, flow *Analysis:* DEGs, Co-expression, MDP, Clustering, Data Integration, Network analysis

    4.  How does the microbiome affect the development of carriage? Data: microbiome Analysis: Microbiome analysis, Network analysis

    5.  <div>

        1.  How the topology of systems biology network change between individuals that develop carriage? Data: all data Analysis: Data Integration, Network analysis

        </div>

2.  **How does sex affect such susceptibility?**

    1.  Is there any perturbation at hormonal levels during carriage development? Data: hormone levels Analysis: Statistics

    2.  How the hormonal levels is related with gene expression signatures associated to development of carriage? Data: hormone levels, rna-seq Analysis: Data Integration, Statistics, Network analysis

    3.  How are hormonal levels related to immunological responses? Data: hormone levels, rna-seq, luminex, flow cytometry Analysis: Data Integration, Statistics, Network analysis

3.  **How ageing can affect the susceptibility to pneumococcal carriage in healthy subjects?**

    Same questions as (1.)

4.  **How vaccination affects the transcriptional and immunological signatures of elderly individuals during pneumococcal carriage?**

    Same questions as (1.), with a special focus at the signatures found in (3.)
