# Pneumococcal Diseases and Immunity

## Controlled Human Infection and Rechallenge with Streptococcus pneumoniae Reveals the Protecticve Efficacy of Carriage in Healty Adults

\- High rates of disease and death in the elderly are associated with low carriage prevalence.

\- Objective: apply an experimental human pneumococcal carriage model ot investigate the immunizing effect of a single carriage episode;

\- Carriage increased both mucosal and serum IgG levels to pneumococcal proteins and polysccharide, resulting in a fourfold increase in opsonophagocytic activity;

\- passive transfer of postcarriage sera from colonized by a heterologous strain in a murine model of invasive pneumococcal pneumonia. These levels were significanlty higher than the protection conferred by either precarriage sera (30%) or saline (10%);

\- Responses elicited by a sigle experimentally induced subsequent carriage and mice against invasive pneumococcal disease by passive transfer of sera from clonized individuals.

\- We have found no relation of baseline serum IgG and carriage outcome after challenge.

\- Intranasal exposure to bacteria boosted serum IgG levels to several pneumococcal prteins, with carriage-positive subjects showing the greatest magnitude of response.

\- Persistent increased IgG to proteins was observed in carriage-positive subjects at 5 weeks after inoculation and not in those without carriage.

\- The boosting effect of exposure is temporary and therefore different than responses induced by persistent carriage. This increased and sustained carriage acquisition after rechallenge up to 11 months after clearance of the first carriage episode.

## Inflammation induced by influenza virus impairs innate control of human pneumococcal carriage

2know:

	- secondary vs primary bacterial penumonia

	- upper respiratory tract

	- human type 6B pneumococcal challenge model

	- degranulation of neutrophils

	- role of neutrophils

	- role of monocytes

	- within-household Spn transmission

	- Live Attenuated Influenza Vaccine

	- murine models

	- 	Th17-dependent recruitment of neutrophils

	- Type I interferons

	- scavenger receptor MARCO

	- double-blinded controlled randomized clinical trial

	- tretavalent inactivated influenza vaccine

	- nasal lining fluid

	- rhinovirus

	- coronavirus

	- respiratory syncytial virus

	- parainfluenzavirus

	- luminal neutrophils

	- myeloperoxidase (marker for neutrophil degranulation)

	- Nanostring expression analysis

	- 80,000 CFU per nostril

	- lytA qPCR

	- systematic LAIV dispensing error

	- Neutrophil opsonophagocytic killing

Primary endpoint:

	- the occurence of pneumococcal colonisation determined by the presence of pneumococcus in nasal wash samples (NW) at any time point post inoculation up to and including day 29.

Secondary endpoint:

	- density of pneumococcal colonisation in NW at each time point following pneumococcal inoculation (days 2, 7, 9, 14, 22 and 29)

	- the are under the curve of pneumococcal colonisation density following pneumococcal inoculation

	- immunological mechanisms associated with altered susceptibility to pneumococcus following LAIV.

\- Flow cytometry analysis:

	- nasal cells

	- whole blood

\- Neutrophil opsonoohagocytic killing

\- Luminex analysis of nasal lining fluid or stimulated nasal cells

\- RNA extraction and sequencing

	- Illumina Hiseq4000, 20M reads, 100 paired-end reads

\- Nanostring

	- Purified blood neutrophils
