# Ageing

## The Hallmarks of Aging

We have two different ages:

	- chronological age

		number of years since you were born

	- biological age

		the time-dependent decline of your body's function and appearance

Chronological and biological age correlate with each other, so the signs of aging appear around a similar chronological age in most people.

But often people exhibit signs of biological aging at very different rates.

Extreme examples can be found in progeroid conditions-congenital disorders that cause the signs of biological aging to begin at a very young age.

In recent years, scientists studying the molecular and cellular processes that govern these changes and their variation in individuals have identified nine interconnected "hallmarks of aging". Determined mainly by our genetics, but modulated by environmental factors, each of these nine hallmarks contributes to the damage that occurs with age and ultimately drives age-associated pathologies.

1) Genomic Instability

2) Telomere attrition

3) Epigenetic alterations

4) Loss of proteostasis

5) Deregulated nutrient sensing

6) Mitochondrial disfunction

7) Cellular senescence

8) Stem cell exhaustion

9) Altered intercellular communication

## Therapies

\- CR mimetics

	may improve nutrient sensing.

\- senolytics

	a class of drug that removes senescent cells.

	- quercetin (The Achilles'heel of senescent cells: from transcriptome to senolytic drugs)

		senolytic treatment using quercetin signifincantly improved vasomotor function in their mouse test group which due to an increase in nitric oxide bioavailability. They also found that clearing senescent cells reduced aortic calcification and osteogenic signalling in both aged and hypercholesterolemic mice. They noted tjat there was no significant effect on intimal plaque fibrosis by treatment.

	

	It has been demonstrated that senescent cells can be cleared selectively by targeting anti-apoptotic proteins Bcl-2 and Ccl-x, using a number of different inhibitors, leading to improved tissue function in mice:

		Zhu, Yi et al. - The Achiles' Heel of Senescet Cells: From Transcriptome to Senolytic Drugs

		Chang, Jianhui et al. - Clearance of Senescent Cells by ABT263 Reuvenates Aged Hematopoietic Stem Cells in Mice

		Discovery of Piperlongumine as a Potential Novel Lead for the Development of Senolytic Agents

		Identification of a Novel Senolytic Agent, Navitoclax, Targeting the Bcl-2 Family of Anti-apoptotic Factors.

	Baar et al. (Targeted Apoptosis of Senescent Cells Restores Tissue Homeostasis in Response to Chemotoxicity and Aging)

	The molecule in the Baar et al. study instead functions by disrupting the interaction between Foxo4 and p53, leading to p53 mediated apoptosis (cell death). The authors have shown that this interaction with Foxo4 inactivates p53 and is restricted specifically to senescent cells. This leads to cell cycle arrest and an inhibition of apoptosis. The molecule itself consists of a small peptide of Foxo4, consisting of D-amino acids, in a retro-reversed sequence, fused to and HIV-Tat domain. The D-amino acids block proteolysis of the compound while the HIV-Tat domain functions as a cell penetrating peptide, enabling the molecule to transverse plasma membranes.

## Senescent Cells

Senescent cells are no longer capable of cell division and they do not support the tissue they are part of. Instead they secreate a cocktail of harmful pro-inflammatory chemical signals that inhibit tissue repair and drive chronic inflammation.

Normally senescent cells are removed and recycled by the immune system but as we age this too begins to decline and more and more senescent cells escape this housekeeping process. It is at that point that cellular senescence ceases being beneficial and protectig us and becomes a driver of the aging process.

Good citizens but bad neihbors - Non-dividing cells would not be a problem themselves but unfortunatelly the secreted pro-inflammatory chemicals they express also encorage nearby healthy cells to enter the same senescent state.

	Collectively this cocktail is known as the Senescent-Associated Secretory Phenotype (SASP)

	SASP:

		(The senescece-associated secretory phenotype: the dark side of tumor suppression)

		- inhibits a number of important cellular processes

		- prevents effective tissue repair

		- contributes to chronic background inflammation

		- is implicated in the onset of age-related diseases (Inflammtory networks during cellular senescence: causes and consequences)

Senescent cells contribute to a second hallmark of aging: altered intercellular communication. This is the age-associated low-grade chronica inflammation many researchers call "inflammaging" and is another hallmark of the aging process.

Inflammaging

	is caused by:

		- infectious burden

		- cell debris

		- excessive activation of the NF-kB protein complex (regulator of the immune response)

		- senescent cell SASP

	interferes with intracellular signalling

	contributes to the loss of regenerative capacity in stem cells and tissues

Senescent cells normally destroy themselves via a programmed process called Apoptosis and they are also removed by the immune systme, however the immune system weakens with age and increasing numbers of these senescent cells escape this process and build up. By the time people reach old age significant numbers of these senescet cells have accumulated in the body and inflammation and damage to surrounding cells and tissue.

## The Role of Senescent Cells in Aging

- profound chromatin and secretome changes

- tumor-suppressor activation

replicative senescence -\> Hayflick - this particular type of senescence is linked to telomere attrition, a process that leads to chromosomal instability and promotes tumorigenesis, supporting the original hypothesis that senescence guards against unrestricted growth of damaged cells.

the physiological relevance of cellular senescence extends beyond tumour suppression into biological processes such as:

	- embryonic development

		10--12

	- wound healing 13

	- tissue repair 14

	- organismal ageing 15,16

Causes and effector pathways of senescence

	Stresses that can induce senescence:

		- telomere erosion

		- DNA lesions

		- ROS

			What they all have in common is that they activate the DNA damage response (DDR), a signaling pathway in which ATM or ATR kinases block cell-cycle progression through stabilization of p53 and transcriptional activation of the cyclin-dependent kinase (Cdk) inhibitor p21.

		- Activated oncogenes

			Oncogenic Ras acts through overexpression of Cdc6 and suppression of nucleotide metabolism, causing aberrant DNA replication, formation of double stranded DNA breaks(DSBs) and activation of the DDR pathway (20,21)

		- senescence caused by E2F3 activation or c-Myc inhibition is DDR-independent and involves p19-Arf and p16-Ink4a (17,22).

		- BRAF (V600E) is also DDR-independent and induces senescence through a metabolic mechanism involving up regulation of mitochondrial pyruvate dehydrogenase(23).

		- various tumour suppressors trigger a senescent growth arrest when inactivated, including RB, PTEN, NF1 and VHL (17,26).

			Of these, RB inactivation engages the DDR (26), whereas the others are DDR-independent and act through p19Arf and p16Ink4a.

		- Prolonged exposure to interferon-b also induces senescence, demonstrating that chronic mitogenic signalling outside the context of neoplastic transformation can stimulate senescence (28).

		- epigenetic, nucleolar and mitotic spindle stresses.

			genome-wide chromatin decompression by exposure to histone deacetylase inhibitors triggers senescence via a p21 dependent mechanism (29).

			A key target of epigenetic stressors that promote senescence may be the INK4a/ARF locus, which in proliferating cells is repressed by polycomb group-mediated H3K27 methylation and H2A-K119 ubiquitination (30). Nucleolar stress caused by RNA polymerase I inhibitors triggers a robust p53-mediated senescence response (31).

		- Senescence can also be elicited by suboptimal expression of proteins implicated in spindle formation or mitotic checkpoint control, including human TACC3 and murine BubR1, Bub3 an dRae1, all of which engage p53 and p21 independently of the DDR, often in combination with p16-Ink4a (15,32,33).

		

A notable species-specific difference is that senescence pathways of murine cells are more dependent on p19Arf than senescence in human cells (27).

Senescence is a multi-step evolving process

Acute vs chronic senescence

Senescence of post-mitotic cells

Senescence in aging and age-related disease

Senescent-cell clearance and future directions
